device: cuda # mps
python_version: ${python_version:micro}

defaults:
  - _self_
  - experiment: multimodal_joint_fusion_classification_with_missing_generation
  - experiment/paths/system@: local  # alvis_snic # local # alvis # SSD
  # - override hydra/launcher: joblib
